# Generated by Django 6.1.1 on 2026-09-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('ultimo_mensaje_entrante', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('texto', models.TextField(blank=True)),
                ('sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chats.contacto')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
    ]
