# Generated by Django 6.1.1 on 2026-10-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True),
        ),
    ]
